openapi: 3.0.1
info:
  title: Product API
  description: API for retrieving product information and reviews
  version: 1.0.0
paths:
  /products:
    get:
      summary: Get all products
      description: Returns a list of all available products
      operationId: getProducts
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetProductsFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /products/{productId}/reviews:
    get:
      summary: Get reviews for a product
      description: Returns reviews for a specific product ID
      operationId: getProductReviews
      parameters:
        - name: productId
          in: path
          description: ID of the product to get reviews for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    type: string
                  reviews:
                    type: array
                    items:
                      $ref: '#/components/schemas/Review'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetProductReviewsFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
components:
  schemas:
    Product:
      type: object
      properties:
        productId:
          type: string
          example: p001
        name:
          type: string
          example: Smartphone X
        price:
          type: number
          format: float
          example: 799.99
        category:
          type: string
          example: Electronics
        description:
          type: string
          example: Latest smartphone with advanced features
    Review:
      type: object
      properties:
        reviewId:
          type: string
          example: r101
        rating:
          type: number
          format: float
          example: 4.5
        comment:
          type: string
          example: Great phone, excellent camera quality!
        reviewer:
          type: string
          example: John D.
        date:
          type: string
          format: date
          example: 2025-03-15
    Error:
      type: object
      properties:
        error:
          type: string
          example: An error occurred
